import io
import os
from xml.sax.saxutils import escape as html_escape
from typing import List, Optional, Any, Dict
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from app.schemas.report import (
    InspectionReportSnapshot,
    OverallDisposition,
    DeclarationFindingItem,
    VisualComplianceFindingItem,
    ExtractedEvidenceItem
)
from app.services.report_service import (
    FSSAI_2026_REGULATORY_NOTE,
    present_finding_reason,
    resolve_evidence_asset,
    resolve_report_disposition,
)


def _register_report_fonts() -> tuple[str, str]:
    """Use an installed Unicode font for Indian currency when available."""
    candidates = [
        (
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        ),
        ("C:/Windows/Fonts/arial.ttf", "C:/Windows/Fonts/arialbd.ttf"),
    ]
    for regular_path, bold_path in candidates:
        if os.path.exists(regular_path) and os.path.exists(bold_path):
            if "DRISHTIUnicode" not in pdfmetrics.getRegisteredFontNames():
                pdfmetrics.registerFont(TTFont("DRISHTIUnicode", regular_path))
                pdfmetrics.registerFont(TTFont("DRISHTIUnicode-Bold", bold_path))
            return "DRISHTIUnicode", "DRISHTIUnicode-Bold"
    return "Helvetica", "Helvetica-Bold"

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and render total page count
    and professional running headers and footers.
    """
    def __init__(self, *args, **kwargs):
        kwargs["pageCompression"] = 0
        super().__init__(*args, **kwargs)
        self.pageCompression = 0
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#475569")) # Slate 600

        # Running Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(36, 11 * 72 - 28, "DRISHTI — Packaged Commodity Legal Metrology Inspection Report")
            self.drawRightString(8.5 * 72 - 36, 11 * 72 - 28, f"Page {self._pageNumber} of {page_count}")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(36, 11 * 72 - 32, 8.5 * 72 - 36, 11 * 72 - 32)

        # Running Footer (all pages)
        footer_y = 28
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, footer_y + 12, 8.5 * 72 - 36, footer_y + 12)

        disclaimer_text = "Generated by DRISHTI — decision-support inspection software. Not a statutory judicial order."
        self.drawString(36, footer_y, disclaimer_text)
        self.drawRightString(8.5 * 72 - 36, footer_y, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def _format_context_value(val: Optional[str]) -> str:
    if not val or val == "UNKNOWN":
        return "Unknown / Not established"
    return val.replace("_", " ")


def _format_normalized_value(val: Optional[Dict[str, Any]]) -> str:
    if not val:
        return "—"
    if "currency" in val and "amount" in val:
        currency = "₹" if val.get("currency") in ("INR", "₹") else str(val.get("currency") or "")
        amount = val.get("amount")
        amount_text = f"{amount:.2f}" if isinstance(amount, (int, float)) else str(amount)
        if "per_unit" in val:
            per_q = val.get("per_quantity", 1.0)
            q_str = f"{per_q} " if per_q != 1.0 else ""
            return f"{currency}{amount_text} / {q_str}{val['per_unit']}"
        return f"{currency}{amount_text}"
    if "value" in val and "unit" in val:
        amount = val["value"]
        amount_text = f"{amount:g}" if isinstance(amount, (int, float)) else str(amount)
        return f"{amount_text} {val['unit']}"
    if "role" in val or "name" in val:
        parts = []
        if val.get("role"):
            parts.append(f"Role: {str(val['role']).replace('_', ' ').title()}")
        if val.get("name"):
            parts.append(f"Entity: {val['name']}")
        if val.get("address"):
            parts.append(f"Address: {val['address']}")
        if val.get("pin_code"):
            parts.append(f"PIN: {val['pin_code']}")
        return " - ".join(parts)
    if "country_text" in val:
        return f"{val.get('declaration_type', 'ORIGIN')}: {val['country_text']}"
    if "name_text" in val:
        return val["name_text"]
    if "month" in val and "year" in val:
        d_type = val.get("type", "DATE")
        day_str = f"{val['day']}/" if val.get("day") else ""
        return f"{d_type} {day_str}{val['month']:02d}/{val['year']}"
    if "email" in val or "phone" in val:
        parts = []
        if val.get("email"):
            parts.append(f"Email: {val['email']}")
        if val.get("phone"):
            parts.append(f"Phone: {val['phone']}")
        return ", ".join(parts)
    
    # Fallback to key-value string
    return ", ".join(f"{k}: {v}" for k, v in val.items() if v is not None)


def _declaration_label(ev: ExtractedEvidenceItem) -> str:
    if ev.field == "MANUFACTURER_PACKER_IMPORTER":
        return "Business Declaration"
    labels = {
        "BRAND_NAME": "Brand",
        "COMMON_GENERIC_NAME": "Product",
        "MRP": "MRP",
        "NET_QUANTITY": "Net Quantity",
        "MONTH_YEAR": "Date Declaration",
        "COUNTRY_OF_ORIGIN": "Country of Origin",
        "CONSUMER_CARE": "Consumer Care",
        "FSSAI_LICENCE": "FSSAI Licence",
        "FSSAI_INGREDIENTS": "Ingredients",
        "FSSAI_ALLERGENS": "Allergens",
        "FSSAI_NUTRITION": "Nutrition",
        "FSSAI_VEG_NONVEG": "Veg / Non-Veg Mark",
    }
    return labels.get(ev.field, ev.field.replace("_", " ").title())


def _final_detected_value(ev: ExtractedEvidenceItem) -> str:
    normalized = _format_normalized_value(ev.normalized_value)
    return normalized if normalized != "—" else (ev.raw_value or "—")


def generate_pdf_report(report: InspectionReportSnapshot) -> bytes:
    """
    Renders an immutable InspectionReportSnapshot into a clean, professional,
    grayscale-printable PDF document using ReportLab.
    """
    regular_font, bold_font = _register_report_fonts()
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=42,
        bottomMargin=42
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Normal'],
        fontName=bold_font,
        fontSize=15,
        leading=18,
        textColor=colors.HexColor('#0F172A')
    )
    subtitle_style = ParagraphStyle(
        'ReportSubtitle',
        parent=styles['Normal'],
        fontName=regular_font,
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#475569')
    )
    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName=bold_font,
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True,
    )
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontName=regular_font,
        fontSize=7.8,
        leading=11,
        textColor=colors.HexColor('#1E293B')
    )
    table_cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName=regular_font,
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#1E293B')
    )
    table_cell_bold = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontName=bold_font,
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#0F172A')
    )
    table_cell_mono = ParagraphStyle(
        'TableCellMono',
        parent=styles['Normal'],
        fontName=regular_font,
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#0F172A')
    )
    disposition_badge_style = ParagraphStyle(
        'DispositionBadge',
        parent=styles['Normal'],
        fontName=bold_font,
        fontSize=8.5,
        leading=10.5,
        alignment=0,
    )

    story = []

    # =========================================================================
    # 1. HEADER & COVER SECTION
    # =========================================================================
    story.append(Paragraph("DRISHTI: PACKAGED COMMODITY INSPECTION REPORT", title_style))
    story.append(Paragraph("Legal Metrology (Packaged Commodities) Rules, 2011 — Decision Support & Evidence Record", subtitle_style))
    story.append(Spacer(1, 8))

    # Metadata Grid Table
    meta = report.metadata
    meta_data = [
        [
            Paragraph("<b>Report ID:</b>", table_cell_style),
            Paragraph(f"<font name='Courier'>{meta.report_id}</font>", table_cell_style),
            Paragraph("<b>Reference Date:</b>", table_cell_style),
            Paragraph(meta.reference_date, table_cell_style),
        ],
        [
            Paragraph("<b>Inspection ID:</b>", table_cell_style),
            Paragraph(f"<font name='Courier'>{meta.inspection_id}</font>", table_cell_style),
            Paragraph("<b>Generated (UTC):</b>", table_cell_style),
            Paragraph(meta.generated_at[:19].replace("T", " "), table_cell_style),
        ],
        [
            Paragraph("<b>Product Category:</b>", table_cell_style),
            Paragraph(meta.product_category.replace("_", " "), table_cell_style),
            Paragraph("<b>Capture Plan:</b>", table_cell_style),
            Paragraph(meta.capture_plan_name or meta.capture_plan_id, table_cell_style),
        ]
    ]

    meta_table = Table(meta_data, colWidths=[90, 180, 90, 180])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 8))

    # Compact overall-disposition summary. The resolved disposition and reason
    # are unchanged; only the page-one presentation is intentionally restrained.
    disp, presented_reason = resolve_report_disposition(report)
    disp_text = str(disp.value if hasattr(disp, "value") else disp).replace("_", " ")

    if disp == OverallDisposition.VIOLATIONS_FOUND:
        disp_bg = colors.HexColor('#FEF2F2')
        disp_border = colors.HexColor('#DC2626')
        disp_text_color = '#991B1B'
    elif disp == OverallDisposition.INCOMPLETE_INSPECTION:
        disp_bg = colors.HexColor('#FFFBEB')
        disp_border = colors.HexColor('#D97706')
        disp_text_color = '#92400E'
    elif disp == OverallDisposition.REVIEW_REQUIRED:
        disp_bg = colors.HexColor('#FEF3C7')
        disp_border = colors.HexColor('#F59E0B')
        disp_text_color = '#B45309'
    else: # NO_VIOLATIONS_DETECTED_IN_EVALUATED_SCOPE
        disp_bg = colors.HexColor('#ECFDF5')
        disp_border = colors.HexColor('#059669')
        disp_text_color = '#065F46'

    disp_badge = Paragraph(f"<font color='{disp_text_color}'>OVERALL DISPOSITION: {disp_text}</font>", disposition_badge_style)
    disp_reason_p = Paragraph(f"<b>Assessment Summary:</b> {presented_reason}", body_style)

    disp_table = Table([[disp_badge, disp_reason_p]], colWidths=[270, 270])
    disp_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), disp_bg),
        ('BACKGROUND', (1, 0), (1, 0), colors.white),
        ('BOX', (0, 0), (-1, -1), 0.6, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('LINEBEFORE', (0, 0), (0, 0), 3.0, disp_border),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
    ]))
    story.append(disp_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 2. SUMMARY COUNTS (DETERMINISTIC CATEGORICAL METRICS ONLY)
    # =========================================================================
    counts = report.summary_counts
    story.append(Paragraph("1. Compliance & Inspection Metrics", section_heading_style))

    statutory_counts_data = [
        [
            Paragraph("<b>Statutory Checks Evaluated</b>", table_cell_bold),
            Paragraph("<b>PASS</b>", table_cell_bold),
            Paragraph("<b>FAIL</b>", table_cell_bold),
            Paragraph("<b>REVIEW REQUIRED</b>", table_cell_bold),
            Paragraph("<b>NOT APPLICABLE</b>", table_cell_bold),
        ],
        [
            Paragraph(str(counts.total_statutory_checks), table_cell_style),
            Paragraph(f"<font color='#059669'><b>{counts.statutory_pass_count}</b></font>", table_cell_style),
            Paragraph(f"<font color='#DC2626'><b>{counts.statutory_fail_count}</b></font>", table_cell_style),
            Paragraph(f"<font color='#D97706'><b>{counts.statutory_review_required_count}</b></font>", table_cell_style),
            Paragraph(f"<font color='#64748B'>{counts.statutory_not_applicable_count}</font>", table_cell_style),
        ]
    ]

    stat_table = Table(statutory_counts_data, colWidths=[180, 90, 90, 90, 90])
    stat_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(stat_table)
    story.append(Spacer(1, 4))

    visual_counts_data = [
        [
            Paragraph("<b>Visual Checks (Rule 7, 8, 9)</b>", table_cell_bold),
            Paragraph("<b>Clear Observation</b>", table_cell_bold),
            Paragraph("<b>Inspector Review Req.</b>", table_cell_bold),
            Paragraph("<b>Not Evaluable from 2D Photo</b>", table_cell_bold),
        ],
        [
            Paragraph(str(counts.total_visual_checks), table_cell_style),
            Paragraph(f"<font color='#059669'>{counts.visual_observation_clear_count}</font>", table_cell_style),
            Paragraph(f"<font color='#D97706'>{counts.visual_review_required_count}</font>", table_cell_style),
            Paragraph(f"<font color='#64748B'>{counts.visual_not_evaluable_count}</font>", table_cell_style),
        ]
    ]

    vis_table = Table(visual_counts_data, colWidths=[180, 120, 120, 120])
    vis_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(vis_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 3. CAPTURE & COVERAGE SUMMARY
    # =========================================================================
    c_sum = report.capture_summary
    story.append(Paragraph("2. Surface Capture & Evidence Sufficiency", section_heading_style))

    capt_status_text = c_sum.capture_status.replace("_", " ")
    suff_text = c_sum.evidence_sufficiency.replace("_", " ")

    capt_info_p = Paragraph(
        f"<b>Capture Status:</b> {capt_status_text} &nbsp;|&nbsp; "
        f"<b>Evidence Sufficiency:</b> {suff_text} &nbsp;|&nbsp; "
        f"<b>Quality:</b> {c_sum.overall_quality_status} &nbsp;|&nbsp; "
        f"<b>Required Views Captured:</b> {c_sum.captured_required_count} of {c_sum.total_views_required}",
        body_style
    )
    story.append(capt_info_p)
    story.append(Spacer(1, 4))

    view_rows = [
        [
            Paragraph("<b>View Role</b>", table_cell_bold),
            Paragraph("<b>Requirement</b>", table_cell_bold),
            Paragraph("<b>Status</b>", table_cell_bold),
            Paragraph("<b>Capture ID</b>", table_cell_bold),
            Paragraph("<b>Image Quality / SHA-256</b>", table_cell_bold)
        ]
    ]

    for v in c_sum.views:
        req_str = "Required" if v.required else "Optional"
        stat_str = "<font color='#059669'>Captured</font>" if v.captured else "<font color='#DC2626'>Missing</font>"
        cap_id_str = f"<font name='Courier'>{v.capture_id[:12]}...</font>" if v.capture_id else "—"
        
        q_notes = []
        if v.quality_status:
            q_notes.append(f"Quality: {v.quality_status}")
        if v.reasons:
            q_notes.extend(v.reasons)
        if v.image_sha256:
            q_notes.append(f"SHA: {v.image_sha256[:16]}...")
        q_str = "; ".join(q_notes) if q_notes else "Acceptable"

        view_rows.append([
            Paragraph(f"{v.display_name} ({v.view_id})", table_cell_style),
            Paragraph(req_str, table_cell_style),
            Paragraph(stat_str, table_cell_style),
            Paragraph(cap_id_str, table_cell_style),
            Paragraph(q_str, table_cell_style),
        ])

    view_table = Table(view_rows, colWidths=[100, 65, 65, 90, 220], repeatRows=1)
    view_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(view_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 4. STATUTORY DECLARATION FINDINGS
    # =========================================================================
    story.append(Paragraph("3A. Legal Metrology Findings", section_heading_style))

    decl_rows = [
        [
            Paragraph("<b>Rule & Declaration</b>", table_cell_bold),
            Paragraph("<b>Legal Ref</b>", table_cell_bold),
            Paragraph("<b>Status</b>", table_cell_bold),
            Paragraph("<b>Statutory Justification / Findings</b>", table_cell_bold),
            Paragraph("<b>Evidence</b>", table_cell_bold)
        ]
    ]

    for f in report.declaration_findings:
        st = f.status
        if st == "PASS":
            st_color = "#059669"
        elif st == "FAIL":
            st_color = "#DC2626"
        elif st == "REVIEW_REQUIRED":
            st_color = "#D97706"
        else:
            st_color = "#64748B"

        status_p = Paragraph(f"<font color='{st_color}'><b>{st}</b></font>", table_cell_style)
        ev_str = ", ".join(eid[:8] for eid in f.evidence_ids) if f.evidence_ids else "—"

        decl_rows.append([
            Paragraph(f"<b>{f.field.replace('_', ' ')}</b><br/><font color='#64748B'>{f.rule_id}</font>", table_cell_style),
            Paragraph(f.legal_reference, table_cell_style),
            status_p,
            Paragraph(present_finding_reason(f, report.inspector_context), table_cell_style),
            Paragraph(f"<font name='Courier' size=6>{ev_str}</font>", table_cell_style)
        ])

    decl_table = Table(decl_rows, colWidths=[110, 85, 75, 200, 70], repeatRows=1)
    decl_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(decl_table)
    story.append(Spacer(1, 10))

    if getattr(report, "food_label_findings", None):
        story.append(Paragraph("3B. Food Labelling / FSSAI Findings", section_heading_style))
        food_rows = [
            [
                Paragraph("<b>Rule & Declaration</b>", table_cell_bold),
                Paragraph("<b>Legal Ref</b>", table_cell_bold),
                Paragraph("<b>Status</b>", table_cell_bold),
                Paragraph("<b>FSSAI Justification / Findings</b>", table_cell_bold),
                Paragraph("<b>Evidence</b>", table_cell_bold)
            ]
        ]
        for f in report.food_label_findings:
            st = f.status
            if st == "PASS":
                st_color = "#059669"
            elif st == "FAIL":
                st_color = "#DC2626"
            elif st == "REVIEW_REQUIRED":
                st_color = "#D97706"
            else:
                st_color = "#64748B"

            status_p = Paragraph(f"<font color='{st_color}'><b>{st}</b></font>", table_cell_style)
            ev_str = ", ".join(eid[:8] for eid in f.evidence_ids) if f.evidence_ids else "—"

            food_rows.append([
                Paragraph(f"<b>{f.field.replace('_', ' ')}</b><br/><font color='#64748B'>{f.rule_id}</font>", table_cell_style),
                Paragraph(f.legal_reference, table_cell_style),
                status_p,
                Paragraph(present_finding_reason(f, report.inspector_context), table_cell_style),
                Paragraph(f"<font name='Courier' size=6>{ev_str}</font>", table_cell_style)
            ])

        food_table = Table(food_rows, colWidths=[110, 85, 75, 200, 70], repeatRows=1)
        food_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(food_table)
        story.append(Paragraph(
            f"<b>Regulatory Notes:</b> {FSSAI_2026_REGULATORY_NOTE}.",
            subtitle_style,
        ))
        story.append(Spacer(1, 10))

    # =========================================================================
    # 5. VISUAL COMPLIANCE FINDINGS (RULE 7, 8, 9)
    # =========================================================================
    story.append(Paragraph("4. Visual Compliance Observations (Rule 7, 8, 9)", section_heading_style))
    story.append(Paragraph(
        "<i>Note: Visual observations reflect 2D image analysis. Technical limitations (e.g. lack of physical scale for Rule 7) "
        "are explicitly marked NOT EVALUABLE and are never converted into false statutory non-compliance.</i>",
        subtitle_style
    ))
    story.append(Spacer(1, 4))

    vis_rows = [
        [
            Paragraph("<b>Visual Check</b>", table_cell_bold),
            Paragraph("<b>Capability</b>", table_cell_bold),
            Paragraph("<b>Observation Status</b>", table_cell_bold),
            Paragraph("<b>Observation & Limitations</b>", table_cell_bold)
        ]
    ]

    for vr in report.visual_compliance_findings:
        v_st = vr.status
        if v_st == "OBSERVATION_CLEAR":
            v_color = "#059669"
        elif v_st == "REVIEW_REQUIRED":
            v_color = "#D97706"
        elif v_st == "NEEDS_RECAPTURE":
            v_color = "#EA580C"
        else:
            v_color = "#64748B"

        obs_status_p = Paragraph(f"<font color='{v_color}'><b>{v_st.replace('_', ' ')}</b></font>", table_cell_style)
        cap_clean = vr.capability.replace("_", " ")

        obs_body = f"<b>Observation:</b> {vr.reason}"
        if vr.limitations:
            obs_body += f"<br/><font color='#64748B'><b>Statutory Limitations:</b> {vr.limitations}</font>"

        vis_rows.append([
            Paragraph(f"<b>{vr.rule_id.replace('_', ' ')}</b><br/><font color='#64748B'>{vr.legal_reference}</font>", table_cell_style),
            Paragraph(cap_clean, table_cell_style),
            obs_status_p,
            Paragraph(obs_body, table_cell_style)
        ])

    vis_table = Table(vis_rows, colWidths=[120, 100, 90, 230], repeatRows=1)
    vis_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(vis_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 6. EXTRACTED DECLARATION EVIDENCE
    # =========================================================================
    story.append(Paragraph("5. Extracted Declaration Evidence", section_heading_style))

    ev_rows = [
        [
            Paragraph("<b>Declaration</b>", table_cell_bold),
            Paragraph("<b>Final Detected Value</b>", table_cell_bold),
            Paragraph("<b>Status</b>", table_cell_bold),
            Paragraph("<b>Evidence Source</b>", table_cell_bold),
            Paragraph("<b>Source View</b>", table_cell_bold)
        ]
    ]

    for ev in report.extracted_evidence:
        view_str = ", ".join(ev.view_ids) if ev.view_ids else "—"

        ev_rows.append([
            Paragraph(f"<b>{_declaration_label(ev)}</b>", table_cell_style),
            Paragraph(_final_detected_value(ev), table_cell_style),
            Paragraph(ev.status.replace("_", " ").title(), table_cell_style),
            Paragraph("Reconciled package evidence", table_cell_style),
            Paragraph(view_str, table_cell_style)
        ])

    if len(ev_rows) > 1:
        ev_table = Table(ev_rows, colWidths=[90, 225, 70, 95, 60], repeatRows=1)
        ev_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(ev_table)
    else:
        story.append(Paragraph("<i>No declaration candidates extracted from provided captures.</i>", body_style))
    story.append(Spacer(1, 10))

    # =========================================================================
    # 6. TRACEABLE EVIDENCE IMAGERY & HIGHLIGHTED REGIONS (APPENDIX)
    # =========================================================================
    story.append(Paragraph("6. Traceable Evidence Imagery & Highlighted Regions", section_heading_style))
    story.append(Paragraph(
        "<i>Annotated optical crops illustrating detected declaration boundaries and statutory context. "
        "All annotations are derivative visual references; source image SHA-256 hashes are strictly preserved.</i>",
        subtitle_style
    ))
    story.append(Spacer(1, 4))

    from app.services.image_store import get_capture_image, get_image_by_hash
    from app.services.evidence_annotation_service import annotate_evidence_crop
    from reportlab.platypus import Image as RLImage
    from PIL import Image as PILImage

    evidence_cards_rendered = 0

    for ev in report.extracted_evidence:
        asset, exact_region_supported, use_polygons = resolve_evidence_asset(report, ev)
        img_bytes = None
        source_sha = asset.image_sha256 if asset else "—"
        source_cap_id = asset.capture_id if asset else "—"
        source_view = asset.view_id if asset else (", ".join(ev.view_ids) if ev.view_ids else "—")

        if asset:
            if getattr(asset, "image_b64", None):
                try:
                    import base64
                    img_bytes = base64.b64decode(asset.image_b64)
                except Exception:
                    img_bytes = None
            if not img_bytes:
                img_bytes = get_capture_image(asset.capture_id) or get_image_by_hash(asset.image_sha256)

        rendered_image = None
        evidence_label = "Contextual visual evidence — exact OCR region unavailable"
        if img_bytes and exact_region_supported:
            rendered_image = annotate_evidence_crop(
                image_bytes=img_bytes,
                field_label=ev.field,
                view_id=source_view,
                polygons=ev.polygons if use_polygons else [],
                pixel_box=ev.pixel_box,
                normalized_box=ev.normalized_box,
                is_clearance=(ev.field == "NET_QUANTITY"),
            )
            if rendered_image:
                evidence_label = "OCR-supported evidence region"
        if img_bytes and not rendered_image:
            rendered_image = img_bytes

        ev_id_str = ", ".join(ev.evidence_ids) if ev.evidence_ids else "—"
        sha_display = f"{source_sha[:16]}..." if source_sha != "—" else "—"
        confidence = f"{int(ev.confidence * 100)}%" if ev.confidence is not None else "—"
        details_html = (
            f"<b>Declaration:</b> {html_escape(_declaration_label(ev))}<br/>"
            f"<b>Final Detected Value:</b> {html_escape(_final_detected_value(ev))}<br/>"
            f"<b>Recorded Package Text:</b> {html_escape(ev.raw_value or '—')}<br/>"
            f"<b>Machine Confidence:</b> {confidence}<br/>"
            f"<b>Evidence ID:</b> <font size=6>{html_escape(ev_id_str)}</font><br/>"
            f"<b>Source Capture:</b> {html_escape(source_view)} ({source_cap_id[:10]}...) &nbsp;|&nbsp; "
            f"<b>SHA:</b> {sha_display}<br/>"
            f"<font color='#64748B'><i>{evidence_label}</i></font>"
        )

        if rendered_image:
            try:
                pil_im = PILImage.open(io.BytesIO(rendered_image))
                pw, ph = pil_im.size
                max_w, max_h = 240, 120
                scale = min(max_w / pw, max_h / ph, 1.0)
                rl_img = RLImage(io.BytesIO(rendered_image), width=pw * scale, height=ph * scale)
                card_table = Table(
                    [[rl_img, Paragraph(details_html, table_cell_style)]],
                    colWidths=[250, 290],
                )
                card_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
                    ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('TOPPADDING', (0, 0), (-1, -1), 4),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                    ('LEFTPADDING', (0, 0), (-1, -1), 6),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ]))
                story.append(KeepTogether([card_table, Spacer(1, 4)]))
                evidence_cards_rendered += 1
            except Exception:
                rendered_image = None

        if not rendered_image and asset:
            fallback_html = details_html + "<br/><font color='#D97706'><i>Source image was unavailable for rendering.</i></font>"
            story.append(Table([[Paragraph(fallback_html, table_cell_style)]], colWidths=[540]))
            story.append(Spacer(1, 4))
            evidence_cards_rendered += 1

    if evidence_cards_rendered == 0:
        story.append(Paragraph("<i>No visual evidence regions available for display.</i>", body_style))
    story.append(Spacer(1, 8))

    # =========================================================================
    # 7. INSPECTOR CONTEXT SNAPSHOT
    # =========================================================================
    story.append(Paragraph("7. Inspector-Provided Context Snapshot", section_heading_style))
    story.append(Paragraph(
        "<i>Explicit contextual parameters supplied by the inspector during progressive clarification. "
        "Unspecified parameters remain 'Unknown / Not established' without silent assumptions.</i>",
        subtitle_style
    ))
    story.append(Spacer(1, 4))

    ctx = report.inspector_context
    ctx_data = [
        [
            Paragraph("<b>Product Origin Classification:</b>", table_cell_style),
            Paragraph(_format_context_value(ctx.product_origin), table_cell_style),
            Paragraph("<b>Regulatory Class:</b>", table_cell_style),
            Paragraph(_format_context_value(ctx.regulatory_product_class), table_cell_style),
        ],
        [
            Paragraph("<b>Date Regime:</b>", table_cell_style),
            Paragraph(_format_context_value(ctx.date_regulatory_regime), table_cell_style),
            Paragraph("<b>Date Exemption:</b>", table_cell_style),
            Paragraph(_format_context_value(ctx.date_package_exemption), table_cell_style),
        ],
        [
            Paragraph("<b>Electronic Commodity:</b>", table_cell_style),
            Paragraph(_format_context_value(ctx.is_electronic), table_cell_style),
            Paragraph("<b>Package Structure:</b>", table_cell_style),
            Paragraph(_format_context_value(ctx.package_structure), table_cell_style),
        ],
        [
            Paragraph("<b>Alcohol Context:</b>", table_cell_style),
            Paragraph(_format_context_value(ctx.alcohol_context), table_cell_style),
            Paragraph("", table_cell_style),
            Paragraph("", table_cell_style),
        ]
    ]

    ctx_table = Table(ctx_data, colWidths=[100, 170, 100, 170])
    ctx_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(ctx_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 8. STATUTORY LIMITATIONS & LEGAL DISCLAIMER
    # =========================================================================
    story.append(Paragraph("8. Statutory & System Limitations", section_heading_style))
    disclaimer_items = [
        "<b>1. Rule 7 Physical Numeral Height:</b> Uncalibrated 2D optical photographs cannot establish absolute millimeter physical dimensions without a certified millimeter calibration target and verified Principal Display Panel area measurement.",
        "<b>2. Rule 8 Principal Display Panel (PDP):</b> The image capture view role 'FRONT' does not automatically constitute the statutory Principal Display Panel as defined under Rule 2(h) of the Legal Metrology Rules, 2011.",
        "<b>3. Rule 9 Color Contrast:</b> Photographic ambient lighting and sensor white-balance vary; definitive background contrast evaluation requires standardized spectrophotometric measurement.",
        "<b>4. Decision Support Notice:</b> This inspection record is generated by DRISHTI for automated decision-support, statutory check verification, and evidence traceability. It does not constitute a judicial certificate or final adjudication order."
    ]

    for item in disclaimer_items:
        story.append(Paragraph(item, body_style))
        story.append(Spacer(1, 2))

    # Build the document
    doc.build(story, canvasmaker=NumberedCanvas)

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
