"""create_rag_table

Revision ID: 7e1846d85f45
Revises: 20260826_7c01
Create Date: 2026-08-27 21:30:36.136132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e1846d85f45'
down_revision: Union[str, None] = '20260826_7c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_knowledge_chunks',
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('regulatory_domain', sa.String(length=50), nullable=False),
    sa.Column('provision_number', sa.String(length=50), nullable=False),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('official_source', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.alter_column('captures', 'field_candidates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('inspections', 'dismissed_clarifications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspections', 'dismissed_clarifications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('captures', 'field_candidates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_table('regulatory_knowledge_chunks')
    # ### end Alembic commands ###
