import { useCallback, useEffect, useState } from 'react';
import { AlertCircle, AlertTriangle, ArrowRight, ClipboardList, Download, FileCheck2, FileText, Plus, ShieldCheck, Users } from 'lucide-react';
import { downloadReportDocx, downloadReportPdf, getDashboardSummary } from '../services/api';

const lifecycleLabels = { DRAFT: 'Draft', IN_PROGRESS: 'In progress', READY_FOR_REVIEW: 'Awaiting review', FINALIZED: 'Finalized' };
const categoryLabel = (value) => ({ GENERIC_RETAIL_PACKAGE: 'Retail package', FOOD: 'Food product', COSMETIC: 'Cosmetic product', DRUG: 'Drug / medical product', NON_FOOD: 'Non-food product', UNKNOWN: 'Not specified' }[value] || value?.replaceAll('_', ' ').toLowerCase() || 'Not specified');
const formatDate = (value) => value ? new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) : 'Not recorded';
const disposition = (item) => {
  if (item.lifecycle_status === 'FINALIZED' && item.overall_disposition === 'INCOMPLETE_INSPECTION') return { label: 'Documented Review Items', className: 'bg-amber-50 text-amber-800 border-amber-200' };
  return ({
    VIOLATIONS_FOUND: { label: 'Possible violations found', className: 'bg-red-50 text-red-800 border-red-200' },
    REVIEW_REQUIRED: { label: 'Officer review required', className: 'bg-amber-50 text-amber-800 border-amber-200' },
    NO_VIOLATIONS_DETECTED_IN_EVALUATED_SCOPE: { label: 'No violations detected', className: 'bg-emerald-50 text-emerald-800 border-emerald-200' },
    INCOMPLETE_INSPECTION: { label: 'Further evidence required', className: 'bg-slate-50 text-slate-700 border-slate-200' },
  })[item.overall_disposition];
};

function MetricCard({ label, value, note, icon: Icon, onClick, tone = 'navy' }) {
  const toneClass = { navy: 'border-blue-200 text-blue-950 bg-blue-50/40', red: 'border-red-200 text-red-900 bg-red-50/50', amber: 'border-amber-200 text-amber-900 bg-amber-50/50', green: 'border-emerald-200 text-emerald-900 bg-emerald-50/50' }[tone];
  return <button type="button" onClick={onClick} className={`portal-interactive min-h-36 border p-5 text-left ${toneClass}`}><div className="flex items-start justify-between gap-3"><span className="text-xs font-bold uppercase tracking-[0.08em] text-slate-600">{label}</span><Icon size={19} /></div><div className="mt-4 text-4xl font-bold tabular-nums">{value ?? 0}</div><p className="mt-2 text-xs text-slate-600">{note}</p></button>;
}

export default function Dashboard({ onStartNew, onOpenInspection, onNavigateToHistory }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await getDashboardSummary()); } catch (err) { setError(err.response?.data?.detail || err.message || 'The dashboard could not be loaded.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  if (loading) return <div className="portal-page py-16 text-center text-sm font-semibold text-slate-600">Loading inspection register…</div>;
  if (error) return <div className="portal-page py-8"><div className="flex items-center justify-between gap-4 border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span className="flex items-center gap-2"><AlertCircle size={18} />{error}</span><button type="button" onClick={load} className="border border-red-300 bg-white px-4 py-2 font-bold">Retry</button></div></div>;

  const { workflow_counts: workflow = {}, attention_counts: attention = {}, report_counts: reports = {}, recent_inspections: recent = [], user_role: role, user_display_name: name, admin_metrics: admin } = data || {};
  const total = workflow.total || 0;
  const attentionTotal = attention.total_needing_attention ?? ((attention.violations_found || 0) + (attention.review_required || 0) + (attention.incomplete_inspection || 0));
  return <main className="portal-page space-y-6 py-6 sm:py-8">
    <section className="portal-card border-t-4 border-t-blue-900 p-5 sm:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-blue-800">{role === 'ADMIN' ? 'Administrative oversight' : 'Officer workspace'}</p><h1 className="mt-1 text-2xl font-bold text-slate-950 sm:text-3xl">Inspection Dashboard</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Overview of packaged commodity inspections and pending officer actions.</p>{name && <p className="mt-1 text-sm text-slate-700">Signed in as <strong>{name}</strong></p>}</div><div className="flex flex-col gap-2 sm:flex-row"><button type="button" onClick={() => onNavigateToHistory?.({})} className="min-h-11 border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-slate-800 hover:bg-slate-50">Open inspection register</button><button type="button" onClick={onStartNew} className="inline-flex min-h-11 items-center justify-center gap-2 bg-blue-900 px-5 py-2 text-sm font-bold text-white hover:bg-blue-800"><Plus size={17} />Inspect product</button></div></div></section>
    {role === 'ADMIN' && admin && <section className="portal-card p-5"><h2 className="portal-section-title"><Users size={18} />Organisation overview</h2><div className="mt-4 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-3">{[['Registered inspectors', admin.total_inspectors], ['Active inspectors', admin.total_active_inspectors], ['System inspections', admin.total_system_inspections]].map(([label, value]) => <div key={label} className="bg-white p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums text-slate-950">{value ?? 0}</p></div>)}</div></section>}
    <section aria-labelledby="overview-title"><div className="mb-3 flex items-end justify-between gap-3"><div><h2 id="overview-title" className="text-lg font-bold text-slate-950">Inspection overview</h2><p className="text-sm text-slate-600">Authoritative counts from the inspection register.</p></div><span className="text-xs font-semibold text-slate-500">{total} total records</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total inspections" value={total} note="All recorded inspections" icon={ClipboardList} onClick={() => onNavigateToHistory?.({})} /><MetricCard label="Possible violations" value={attention.violations_found} note="Confirmed non-compliance findings" icon={AlertCircle} tone="red" onClick={() => onNavigateToHistory?.({ disposition: 'VIOLATIONS_FOUND' })} /><MetricCard label="Needs officer review" value={attention.review_required} note="Unresolved officer-review records" icon={AlertTriangle} tone="amber" onClick={() => onNavigateToHistory?.({ disposition: 'REVIEW_REQUIRED' })} /><MetricCard label="Finalized inspections" value={workflow.finalized} note="Approved and immutable reports" icon={FileCheck2} tone="green" onClick={() => onNavigateToHistory?.({ lifecycle_status: 'FINALIZED' })} /></div></section>
    <section className="portal-card p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 pb-4"><div><h2 className="text-lg font-bold text-slate-950">Attention required</h2><p className="mt-1 text-sm text-slate-600">Open the relevant register view to continue the officer workflow.</p></div><span className="border border-slate-300 bg-slate-50 px-3 py-1 text-sm font-bold tabular-nums text-slate-800">{attentionTotal} records require attention</span></div><div className="mt-4 grid gap-3 lg:grid-cols-3">{[['Confirmed non-compliance', attention.violations_found, 'VIOLATIONS_FOUND', AlertCircle, 'text-red-800'], ['Officer review required', attention.review_required, 'REVIEW_REQUIRED', AlertTriangle, 'text-amber-800'], ['Additional package evidence required', attention.incomplete_inspection, 'INCOMPLETE_INSPECTION', ShieldCheck, 'text-slate-800']].map(([label, value, filter, Icon, tone]) => <button key={label} type="button" onClick={() => onNavigateToHistory?.({ disposition: filter })} className="portal-interactive flex min-h-24 items-center justify-between border border-slate-200 bg-white p-4 text-left"><span className={`flex items-center gap-3 text-sm font-bold ${tone}`}><Icon size={20} />{label}</span><span className="text-2xl font-bold tabular-nums text-slate-950">{value ?? 0}</span></button>)}</div></section>
    <section className="portal-card overflow-hidden"><div className="flex items-center justify-between gap-4 border-b border-slate-200 px-5 py-4 sm:px-6"><div><h2 className="text-lg font-bold text-slate-950">Recent inspections</h2><p className="text-sm text-slate-600">Most recently updated records.</p></div><button type="button" onClick={() => onNavigateToHistory?.({})} className="inline-flex items-center gap-1 text-sm font-bold text-blue-900 hover:underline">View all <ArrowRight size={15} /></button></div>
      {recent.length === 0 ? <div className="p-10 text-center"><FileText className="mx-auto text-slate-400" /><p className="mt-3 text-sm text-slate-600">No inspections have been recorded.</p><button type="button" onClick={onStartNew} className="mt-4 bg-blue-900 px-4 py-2 text-sm font-bold text-white">Start inspection</button></div> : <div className="overflow-x-auto"><table className="w-full min-w-[920px] border-collapse text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr><th className="px-5 py-3">Product category</th><th className="px-4 py-3">Last updated</th><th className="px-4 py-3">Captures</th><th className="px-4 py-3">Workflow</th><th className="px-4 py-3">Finding</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-200">{recent.map((item) => { const finding = disposition(item); const finalized = item.lifecycle_status === 'FINALIZED'; return <tr key={item.inspection_id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold text-slate-900">{categoryLabel(item.product_category)}{item.created_by_username && <span className="mt-1 block text-xs font-normal text-slate-500">Inspector: {item.created_by_username}</span>}</td><td className="px-4 py-4 text-slate-600">{formatDate(item.updated_at)}</td><td className="px-4 py-4 tabular-nums text-slate-700">{item.capture_count ?? 0}</td><td className="px-4 py-4"><span className="border border-slate-300 bg-white px-2 py-1 text-xs font-semibold text-slate-700">{lifecycleLabels[item.lifecycle_status] || 'Draft'}</span></td><td className="px-4 py-4">{finding ? <span className={`border px-2 py-1 text-xs font-semibold ${finding.className}`}>{finding.label}</span> : <span className="text-xs text-slate-500">Not evaluated</span>}</td><td className="px-5 py-4"><div className="flex justify-end gap-2">{item.has_report && <><button type="button" onClick={() => downloadReportPdf(item.inspection_id)} className="border border-slate-300 bg-white px-3 py-2 text-xs font-bold">PDF</button><button type="button" onClick={() => downloadReportDocx(item.inspection_id)} className="border border-slate-300 bg-white px-3 py-2 text-xs font-bold"><Download size={13} className="inline" /> Word</button></>}<button type="button" onClick={() => onOpenInspection(item.inspection_id)} className="bg-blue-900 px-3 py-2 text-xs font-bold text-white">{finalized ? 'View record' : 'Continue'}</button></div></td></tr>; })}</tbody></table></div>}
      {(reports.generated || reports.available) != null && <div className="border-t border-slate-200 bg-slate-50 px-5 py-3 text-xs text-slate-600">Finalized report register: <strong>{reports.generated ?? reports.available ?? 0}</strong></div>}
    </section>
  </main>;
}
